#!/bin/bash


# There are 3 different models for the journaller,
#
#   * serial - one process, read from socket then write to file
#   * thread - 2 threads, one reads from socket putting events into a queue,
#              the second writes to a file
#   * process - 2 processes, one reads from socket putting events into a queue,
#               the second writes to a file
#
# The thread or process models should minimize event loss.
model=thread

# Try to get the IP address for the mondemand server from
# the mondemand config file. If we cannot find the file
# we just send to localhost, which will probably not do anything.
MONDEMAND_CONFIG=/etc/mondemand/mondemand.conf
MONDEMAND_ADDR=127.0.0.1
MONDEMAND_PORT=11111
MONDEMAND_TTL=10
if [ -f $MONDEMAND_CONFIG ] ;
then
  source $MONDEMAND_CONFIG
fi

# -----------------------------------------------------------------------
# The following are actually used by the journaller init script, or the
# system scripts
# -----------------------------------------------------------------------
# allow core files
DAEMON_COREFILE_LIMIT='unlimited'

# options for journaller
OPTIONS="--address=127.0.0.1 --port=22222 --real-time --log-level=15 --log-file=/var/log/lwes-journaller/lwes-journaller.log --user=journaller --thread-type=$model --mondemand-ip=$MONDEMAND_ADDR --mondemand-port=$MONDEMAND_PORT --mondemand-ttl=$MONDEMAND_TTL /var/lib/lwes-journaller/journals/outbound/all_events.log.gz"
